const salesData = [
  {
    id: 1,
    image: "/assets/imgs/FSImgs/image1.png",
    name: "Kabir Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    description:
      " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space.",
  },
  {
    id: 2,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    description:
      "Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space."
  },
  {
    id: 3,
    image: "/assets/imgs/FSImgs/image3.png",
    name: "Chidi Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    description:
      " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space.",
  },
  {
    id: 4,
    image: "/assets/imgs/FSImgs/image44.png",
    name: "Zadok Chair",
    slashPrice: "110",
    prevPrice: "180",
    rating: "",
    badgeValue: "-20%",
    description:
      " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space. ",
  },
  {
    id: 5,
    image: "/assets/imgs/FSImgs/image5.png",
    name: "Lanre Chair",
    slashPrice: "110",
    prevPrice: "170",
    rating: "",
    badgeValue: "-20%",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 6,
    image: "/assets/imgs/FSImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 7,
    image: "/assets/imgs/FSImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    description:
      " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space. ",
  },
  {
    id: 8,
    image: "/assets/imgs/FSImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    description:
      " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space. ",
  },
];

const BSProdData = [
  {
    id: 1,
    image: "/assets/imgs/BSPImgs/image1.png",
    name: "Kabir Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    description:
      " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space. ",
  },
  {
    id: 2,
    image: "/assets/imgs/BSPImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    description:
      "Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space.  ",
  },
  {
    id: 3,
    image: "/assets/imgs/BSPImgs/image3.png",
    name: "Chidi Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    description:
      " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space. ",
  },
  {
    id: 4,
    image: "/assets/imgs/BSPImgs/image4.png",
    name: "Zadok Chair",
    slashPrice: "110",
    prevPrice: "180",
    rating: "",
    badgeValue: "-20%",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 5,
    image: "/assets/imgs/BSPImgs/image5.png",
    name: "Lanre Chair",
    slashPrice: "110",
    prevPrice: "170",
    rating: "",
    badgeValue: "-20%",
    description:
      "Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space.  ",
  },
  {
    id: 6,
    image: "/assets/imgs/BSPImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
];

const products = [
  {
    id: 1,
    image: "/assets/imgs/sofa/sofa2.png",
    name: "Dion Sofa",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "sofa",
    description:
      " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space. ",
  },
  {
    id: 2,
    image: "/assets/imgs/Dsets/set4.png",
    name: "Sophie Dining Set",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "d-set",
    description:
      " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space. ",
  },
  {
    id: 3,
    image: "/assets/imgs/BSPImgs/image3.png",
    name: "Khandy Accessories",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "accessories",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 4,
    image: "/assets/imgs/tables/tabbe3.png",
    name: "Zaron Table",
    slashPrice: "110",
    prevPrice: "180",
    rating: "",
    badgeValue: "-20%",
    category: "table",
    description:
      " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space. ",
  },
  {
    id: 5,
    image: "/assets/imgs/BSPImgs/image5.png",
    name: "Lanre Table",
    slashPrice: "110",
    prevPrice: "170",
    rating: "",
    badgeValue: "-20%",
    category: "table",
    description:
      " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space. ",
  },
  {
    id: 6,
    image: "/assets/imgs/BSPImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "sofa",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 7,
    image: "/assets/imgs/chairs/chair1.png",
    name: "Kabir Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
    description:
      " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space. ",
  },

  {
    id: 8,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 9,
    image: "/assets/imgs/sofa/sofa3.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "sofa",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 10,
    image: "/assets/imgs/sofa/sofa4.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "sofa",
    description:
      " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space. ",
  },
  {
    id: 11,
    image: "/assets/imgs/tables/table4.png",
    name: "Enne Side Table",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "table",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 12,
    image: "/assets/imgs/NewInImgs/image1.png",
    name: "Blair Dining Set",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "d-set",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 13,
    image: "/assets/imgs/tables/table1.png",
    name: "Sally Side Table",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "table",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 14,
    image: "/assets/imgs/chairs/chair4.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 15,
    image: "/assets/imgs/tables/table2.png",
    name: "Ese Side Table",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "table",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 16,
    image: "/assets/imgs/Dsets/set2.png",
    name: "Saline Dining Set",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "d-set",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 17,
    image: "/assets/imgs/Dsets/set1.png",
    name: "Kayla Dining Set",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "d-set",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 18,
    image: "/assets/imgs/accessories/acc3.png",
    name: "Khandy Accessories",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "accessories",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 19,
    image: "/assets/imgs/accessories/acc2.png",
    name: "Kunle Accessories",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "accessories",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 20,
    image: "/assets/imgs/accessories/acc4.png",
    name: "Wade Accessories",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "accessories",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 21,
    image: "/assets/imgs/accessories/acc1.png",
    name: "Femi Accessories",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "accessories",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?",
  },
  {
    id: 7,
    image: "/assets/imgs/chairs/chair2.png",
    name: "Unknown Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
    description: " Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space. ",
  },
  {
    id: 7,
    image: "/assets/imgs/chairs/chair3.png",
    name: "Lade Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
    description:
      "Enjoy unparalleled comfort and timeless elegance with our product. It is meticulously crafted to perfection, and combines sophisticated design with the finest materials, making it the quintessential addition to any luxurious living space.",
  },
];

export { salesData, BSProdData, products };

// &#36;
